feat(networking): functionalities required for connecting wifi with credentials and resolves #2
bug(compiling): unable to compile code due to some libray
inconsistencies

```bash
  129 |   const char *eventName(arduino_event_id_t id);
      |                         ^~~~~~~~~~~~~~~~~~
/home/***/.arduino15/packages/esp32/hardware/esp32/3.0.2/libraries/WiFi/src/WiFiGeneric.h:131:30: error: 'arduino_event_t' has not been declared
  131 |   static void _eventCallback(arduino_event_t *event);
      |                              ^~~~~~~~~~~~~~~
/home/***/.arduino15/packages/esp32/hardware/esp32/3.0.2/libraries/WiFi/src/WiFiGeneric.h:83:68: error: 'ARDUINO_EVENT_MAX' was not declared in this scope; did you mean 'WIFI_EVENT_MAX'?
   83 |   void removeEvent(WiFiEventCb cbEvent, arduino_event_id_t event = ARDUINO_EVENT_MAX);
      |                                                                    ^~~~~~~~~~~~~~~~~
      |                                                                    WIFI_EVENT_MAX
/home/***/.arduino15/packages/esp32/hardware/esp32/3.0.2/libraries/WiFi/src/WiFiGeneric.h:84:71: error: 'ARDUINO_EVENT_MAX' was not declared in this scope; did you mean 'WIFI_EVENT_MAX'?
   84 |   void removeEvent(WiFiEventSysCb cbEvent, arduino_event_id_t event = ARDUINO_EVENT_MAX);
      |                                                                       ^~~~~~~~~~~~~~~~~
      |                                                                       WIFI_EVENT_MAX
/home/***/.arduino15/packages/esp32/hardware/esp32/3.0.2/libraries/WiFi/src/WiFiSTA.h:44:42: error: expected class-name before '{' token
   44 | class STAClass : public NetworkInterface {
      |                                          ^
In file included from /home/***/.arduino15/packages/esp32/hardware/esp32/3.0.2/libraries/WiFi/src/WiFi.h:34:
/home/***/.arduino15/packages/esp32/hardware/esp32/3.0.2/libraries/WiFi/src/WiFiAP.h:39:41: error: expected class-name before '{' token
   39 | class APClass : public NetworkInterface {
      |                                         ^

exit status 1

Compilation error: exit status 1
```